name: Build & Test Zappy AI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y python3 python3-pip
      
      - name: Build project
        run: make zappy_ai
        timeout-minutes: 1
      
      - name: Verify executable exists
        run: |
          if [ ! -f ./zappy_ai ]; then
            echo "Error: can't find zappy_ai executable at root"
            exit 1
          fi
      
      - name: Test AI help command
        run: |
          ./zappy_ai --help
        timeout-minutes: 1
      
      # - name: Run unit tests
      #   run: |
      #     cd ai && python -m pytest tests/
      #   timeout-minutes: 1
